name: Vetube-x86

on:
  push:
    tags: ["*"]
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Source checkout
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x86

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compiling
        run: pyinstaller vetube.py

      - name: Create zip
        run: zip -r vetube-x86.zip dist/

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: vetube
          path: vetube-x86.zip

  vetube_release:
    runs-on: windows-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build"]
    steps:
    - uses: actions/checkout@v3
    - name: download
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: vetube-x86.zip
        fail_on_unmatched_files: true
        prerelease: ${{ contains(github.ref, '-') }}
