name: VeTube-x86

on:
  push:
    tags: ["*"]
    branches: [ master , piper ]
  pull_request:
    branches: [ master , piper ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Source checkout
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
          architecture: x86

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller gdown
          pip install --upgrade pyzmq httpx httpcore future
          git clone https://github.com/mush42/espeak-phonemizer-windows

      - name: Compiling
        run: |
          pyinstaller VeTube.py --windowed
          gdown 1ZtF6zus0A7kC9Lwr_kTUbw0MiOoZq29H -O dist/VeTube/bootstrap.exe
          cp -R chat_downloader dist/VeTube/
          cp -R doc dist/VeTube/
          cp -R locales dist/VeTube/
          cp -R sounds dist/VeTube/
          cp -R espeak-phonemizer-windows/espeak_phonemizer dist/VeTube/

      - name: Create zip
        run: |
          cd dist/VeTube
          7z a ../VeTube-x86.zip ./
          cd ..

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: VeTube-x86
          path: dist
          if-no-files-found: error

  vetube_release:
    runs-on: windows-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build"]
    steps:
    - uses: actions/checkout@v3
    - name: download
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: VeTube-x86.zip
        fail_on_unmatched_files: true
        prerelease: ${{ contains(github.ref, '-') }}
