name: Vetube-x64

on:
  push:
    tags: ["*"]
    branches:
      - master
      piper
  pull_request:
    branches:
      - master
      piper
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Source checkout
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          git clone https://github.com/mush42/espeak-phonemizer-windows

      - name: Compiling
        run: |
          pyinstaller vetube.py
          cp -R doc dist/
          cp -R locales dist/
          cp -R readme dist/
          cp -R sounds dist/
          cp -R espeak-phonemizer-windows/espeak_phonemizer dist/

      - name: Create zip
        run: zip -r vetube-x64.zip dist/

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: vetube
          path: vetube-x64.zip

  vetube_release:
    runs-on: windows-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build"]
    steps:
    - uses: actions/checkout@v3
    - name: download
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: vetube-x64.zip
        fail_on_unmatched_files: true
        prerelease: ${{ contains(github.ref, '-') }}
